-- APPLICATION_HEAD_INFO
INSERT INTO APPLICATION_HEAD_INFO(APPLICATION_ID,HEAD_FIRST_NAME,HEAD_MIDDLE_NAME,HEAD_LAST_NAME,SUFFIX,DATE_OF_BIRTH,GENDER,STATUS) VALUES('A-001','JOHN','','CENA','','1984-05-03','Male','Pending');
INSERT INTO APPLICATION_HEAD_INFO(APPLICATION_ID,HEAD_FIRST_NAME,HEAD_MIDDLE_NAME,HEAD_LAST_NAME,SUFFIX,DATE_OF_BIRTH,GENDER,STATUS) VALUES('A-002','SMITH','','ROCENA','Mr.','1994-08-23','Male','Approved');
INSERT INTO APPLICATION_HEAD_INFO(APPLICATION_ID,HEAD_FIRST_NAME,HEAD_MIDDLE_NAME,HEAD_LAST_NAME,SUFFIX,DATE_OF_BIRTH,GENDER,STATUS) VALUES('A-003','JAMES','SMITH','RECENAT','','1976-01-25','Male','Denied');
INSERT INTO APPLICATION_HEAD_INFO(APPLICATION_ID,HEAD_FIRST_NAME,HEAD_MIDDLE_NAME,HEAD_LAST_NAME,SUFFIX,DATE_OF_BIRTH,GENDER,STATUS) VALUES('A-004','TONY','','STARK','Mr.','1986-06-13','Male','Pending');
INSERT INTO APPLICATION_HEAD_INFO(APPLICATION_ID,HEAD_FIRST_NAME,HEAD_MIDDLE_NAME,HEAD_LAST_NAME,SUFFIX,DATE_OF_BIRTH,GENDER,STATUS) VALUES('A-005','Hande','VRU','Ercel','Miss','1994-12-03','FeMale','Approved');



-- APPLICATION_MEMBER_INFO
INSERT INTO APPLICATION_MEMBER_INFO(MEMBER_ID,MEMBER_FIRST_NAME,MEMBER_MIDDLE_NAME,MEMBER_LAST_NAME,SUFFIX,DATE_OF_BIRTH,GENDER,APPLICATION_ID,RELATION) VALUES('M-001','FIZA','','HUSSAIN','Miss','1974-08-13','Female','A-001','Daughter');
INSERT INTO APPLICATION_MEMBER_INFO(MEMBER_ID,MEMBER_FIRST_NAME,MEMBER_MIDDLE_NAME,MEMBER_LAST_NAME,SUFFIX,DATE_OF_BIRTH,GENDER,APPLICATION_ID,RELATION) VALUES('M-002','REHMAT','RAJAB','HUSSAIN','Mr','1976-09-03','Male','A-001','Son');
INSERT INTO APPLICATION_MEMBER_INFO(MEMBER_ID,MEMBER_FIRST_NAME,MEMBER_MIDDLE_NAME,MEMBER_LAST_NAME,SUFFIX,DATE_OF_BIRTH,GENDER,APPLICATION_ID,RELATION) VALUES('M-003','MURAAD','','ALI','','1997-07-03','Male','A-002','Brother');
INSERT INTO APPLICATION_MEMBER_INFO(MEMBER_ID,MEMBER_FIRST_NAME,MEMBER_MIDDLE_NAME,MEMBER_LAST_NAME,SUFFIX,DATE_OF_BIRTH,GENDER,APPLICATION_ID,RELATION) VALUES('M-004','AAYAN','','HUSSAIN','Mr.','1996-05-03','Male','A-005','Brother');

