create database census_app_db;
use census_app_db;


-- APPLICATION_HEAD_INFO
CREATE TABLE APPLICATION_HEAD_INFO
(
 APPLICATION_ID VARCHAR(5),
 HEAD_FIRST_NAME VARCHAR(30),
 HEAD_MIDDLE_NAME VARCHAR(30),
 HEAD_LAST_NAME VARCHAR(30),
 SUFFIX VARCHAR(10),
 DATE_OF_BIRTH  DATE,
 GENDER VARCHAR(10),
 STATUS VARCHAR(20),
 CONSTRAINT APP_HEAD_INFO_PK PRIMARY KEY(APPLICATION_ID)
);

-- APPLICATION_MEMBER_INFO
CREATE TABLE APPLICATION_MEMBER_INFO
(
 MEMBER_ID VARCHAR(5),
 MEMBER_FIRST_NAME VARCHAR(30),
 MEMBER_MIDDLE_NAME VARCHAR(30),
 MEMBER_LAST_NAME VARCHAR(30),
 SUFFIX VARCHAR(10),
 DATE_OF_BIRTH  DATE,
 GENDER VARCHAR(10),
 APPLICATION_ID VARCHAR(5),
 RELATION VARCHAR(20),
 CONSTRAINT APP_MEM_INFO_PK PRIMARY KEY(MEMBER_ID),
 CONSTRAINT APP_HEAD_INFO_FK FOREIGN KEY(APPLICATION_ID) REFERENCES APPLICATION_HEAD_INFO(APPLICATION_ID)
);

